version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: disabled
