name: build-ios-ipa

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
      with:
        xcode-version: '26.0'

    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Install npm dependencies and add dummy version to package.json
      run: |
        sed -i.bak "s/%LINK_VERSION%/0.0.1/g" package.json
        cd example
        rm -rf node_modules
        npm config set cache "$HOME/.npm-cache"
        npm cache clean --force
        npm install --force

    - name: Overwrite index.js
      run: |
        cd example
        rm index.js
        mv json-demo-build.js index.js

    - name: Overwrite node module
      run: |
        rsync -Rr . example/node_modules/@argyleio/argyle-plugin-react-native

    - name: Import Codesigning Certificate
      uses: apple-actions/import-codesign-certs@63fff01cd422d4b7b855d40ca1e9d34d2de9427d # v3.0.0
      with:
        p12-file-base64: ${{ secrets.ARGYLE_LINK_IOS_SIGNING_CERT_P12 }}
        p12-password: ${{ secrets.ARGYLE_LINK_IOS_SIGNING_CERT_PASS }}

    - name: Install Provisioning Profile
      uses: akiojin/install-provisioning-profile-github-action@e3f58307bd921490aed4691bb568ce4eb2849c62 # v1.0
      with:
        base64: ${{ secrets.ARGYLE_LINK_IOS_SIGNING_PROVISIONING }}

    - name: Patch Boost podspec to remove sha256 checksum
      run: |
        cd example
        perl -0777 -pi -e "s#:http\s*=>\s*'[^']*'#:http => 'https://downloads.sourceforge.net/project/boost/boost/1.83.0/boost_1_83_0.tar.bz2'#g" node_modules/react-native/third-party-podspecs/boost.podspec
        perl -0777 -pe "s/\s*,?\s*:sha256\s*=>\s*'[^']*'//g" -i node_modules/react-native/third-party-podspecs/boost.podspec
        echo "Modified podspec:"
        cat node_modules/react-native/third-party-podspecs/boost.podspec

    - name: Cocoapods install
      run: |
        sudo gem install cocoapods -v 1.16.2
        cd example/ios
        pod install --clean-install

    - name: Build App
      run: |
        cd example/ios
        xcodebuild -workspace LinkReactNative.xcworkspace -scheme LinkReactNative -configuration Release -sdk iphoneos -archivePath demo.xcarchive archive CODE_SIGN_STYLE=Manual
        xcodebuild -exportArchive -archivePath ./demo.xcarchive -exportOptionsPlist ../../.github/configs/exportOptions.plist -exportPath build-demo

    - name: Archive IPA
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ipa-LinkReactNative
        path: example/ios/build-demo/LinkReactNative.ipa
